[package]
name = "cortex_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.9"
chrono = "0.4"
rfd = "0.11"
notify = "6.1"
notify-debouncer-mini = "0.4"
rusqlite = "0.29"
directories = "5.0"
